### ISSUE TITLE
Стандартная ситуация с WAL и контроль за ошибками в mamonsu

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#148]
Новый плагин падает когда попадает на момент окончания докачки очередного WAL файла
```
[ERROR] 2020-09-09 11:27:29,446 - PGPROBACKUP   -       catch error: [Errno 2] No such file or directory: '/mnt/pgbak/wal/11/0000000100000AF700000059.gz.part'
```
и в zabbix:
```
Mamonsu plugin errors on mkgu-pg02. Last: catch error: [Errno 2] No such file or directory: '/mnt/pgbak/wal/11/0000000100000AF700000059.gz.part'. Total count: 1
```
предлагаю встроить контроль за ошибками внутрь плагина и не падать при такой ситуации.

**Comment by popov83** [comment]
уточните пожалуйста, на какой метрике падает, на 'pg_probackup.dir.size или g_probackup.dir.error ?

**Comment by sgrinko** [comment]
В режиме INFO такой информации нет...
Включил DEBUG в надежде, что в скором времени попаду на эту ситуацию...
но может быть вы просто это сможете смоделировать быстрее чем я смогу это получить на живой системе ?

**Comment by sgrinko** [comment]
В режиме DEBUG получил:
```
[ERROR] 2020-09-09 15:26:36,924 - PGPROBACKUP   -       catch error: [Errno 2] No such file or directory: '/mnt/pgbak/wal/11/0000000100000AF7000000BD.gz.part'
[INFO] 2020-09-09 15:26:36,924 - PGPROBACKUP    -       hint: enable debug level to full exception trace
[DEBUG] 2020-09-09 15:26:36,924 - PGPROBACKUP   -       Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mamonsu/lib/plugin.py", line 162, in _loop
    self.run(self.sender)
  File "/usr/lib/python3/dist-packages/mamonsu/plugins/system/linux/pg_probackup.py", line 56, in run
    dir_size = self.dir_size(_dir)
  File "/usr/lib/python3/dist-packages/mamonsu/plugins/system/linux/pg_probackup.py", line 27, in dir_size
    size = os.path.getsize(os.path.join(dirpath, file))
  File "/usr/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/pgbak/wal/11/0000000100000AF7000000BD.gz.part'
```
достаточно для решения проблемы ?

**Comment by popov83** [comment]
да, достаточно. 
Ошибка в pg_probackup.dir.size, при определении размера.

**Comment by popov83** [comment]
Ошибка исправлена в новой версии. Попробуйте пожалуйста.

**Comment by sgrinko** [comment]
попытаемся... это непросто... предлагаю закрыть issue. Если проблема снова всплывёт, то я заведу новую.
