### ISSUE TITLE
Ошибка при генерации шаблона (версия 3.0.0)

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#164]
Ошибка при генерации шаблона

```
$ mamonsu export template template.xml
Traceback (most recent call last):
  File "/bin/mamonsu", line 11, in <module>
    load_entry_point('mamonsu==3.0.0', 'console_scripts', 'mamonsu')()
  File "/usr/lib/python3.6/site-packages/mamonsu/lib/runner.py", line 150, in start
    fd.write(template.xml("all", plugins))  # set type to 'all' for mamonsu
  File "/usr/lib/python3.6/site-packages/mamonsu/lib/zbx_template.py", line 172, in xml
    template_data['discovery_rules'] = self._get_all('discovery_rules', plugins)
  File "/usr/lib/python3.6/site-packages/mamonsu/lib/zbx_template.py", line 187, in _get_all
    row = getattr(plugin, items)(self, dashboard=False)  # get Items of this particular plugin
TypeError: discovery_rules() got an unexpected keyword argument 'dashboard'
```

**Comment by sgrinko** [comment]
Я увидел выпуск версии 3.0.1, это конечно хорошо, но а как же эта проблема?
Это ведь серьёзно!

**Comment by sgrinko** [comment]
Попробовал на версии 3.0.1
Падения нет. Сорри, продолжаю тестировать ....
Задачку можно закрыть
