### ISSUE TITLE
ARCHIVECOMMAND - plugin archivecommand caught error: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#203]
Добрый день,
при рестарте mamonsu часто вылетает такая ошибка:
```
[ERROR] 2023-06-29 08:56:34,509 - ARCHIVECOMMAND    -   plugin archivecommand caught error: '<' not supported between instances of 'int' and 'str'
[INFO] 2023-06-29 08:56:34,509 - ARCHIVECOMMAND -   hint: enable debug level to full exception trace
[DEBUG] 2023-06-29 08:56:34,509 - ARCHIVECOMMAND    -   Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mamonsu-3.5.3-py3.6.egg/mamonsu/lib/plugin.py", line 173, in _loop
    self.run(self.sender)
  File "/usr/local/lib/python3.6/site-packages/mamonsu-3.5.3-py3.6.egg/mamonsu/plugins/pgsql/archive_command.py", line 90, in run
    self.disable_and_exit_if_archive_mode_is_not_on()
  File "/usr/local/lib/python3.6/site-packages/mamonsu-3.5.3-py3.6.egg/mamonsu/plugins/pgsql/plugin.py", line 58, in disable_and_exit_if_archive_mode_is_not_on
    param = Pooler.get_sys_param('archive_mode', db=db)
  File "/usr/local/lib/python3.6/site-packages/mamonsu-3.5.3-py3.6.egg/mamonsu/plugins/pgsql/driver/pool.py", line 310, in get_sys_param
    if self.is_bootstraped() and self.bootstrap_version_greater("2.3.4"):
  File "/usr/local/lib/python3.6/site-packages/mamonsu-3.5.3-py3.6.egg/mamonsu/plugins/pgsql/driver/pool.py", line 143, in bootstrap_version_greater
    self._cache["bootstrap"]["version"]) >= LooseVersion(version)
  File "/usr/lib64/python3.6/distutils/version.py", line 58, in __le__
    c = self._cmp(other)
  File "/usr/lib64/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```
вероятно выполняется не в то время инициализация значения во внутреннем кэше
Поправьте пожалуйста

**Comment by xinferum** [comment]
Дополню - похоже эта ошибка возникает не только при рестарте/запуске mamonsu.
